#include <HardwareSerial.h>

#ifdef TARGET_BLUEPILL
  #define LED_BUILTIN PB2
  #define LED_ACTIVE_LOW false
  //HardwareSerial Serial1(USART1); // PB6, PB7, TX, RX - commented out as already defined in arduino variant file and redefinition causes compile error
  HardwareSerial Serial2(USART2); // PA2, PA3, TX, RX
  HardwareSerial Serial3(USART3); // PB10, PB11 TX, RX
  #define SERIAL1_TX PB6
  #define SERIAL1_RX PB7
  #define SERIAL2_TX PA2
  #define SERIAL2_RX PA3
  #define SERIAL3_TX PB10
  #define SERIAL3_RX PB11

  uint32_t PWM_Tim_Pin_Map[10] = {PA0,PA1,PA6,PA7_ALT1,PB0_ALT1,PB1_ALT1,PA8,PA9,PA10,PB8}; // PA11 did not work so PB8 used instead Timer4 channel 3 compromising I2C1 SCL pin
  #define SDA1 PB9
  #define SCL1 PB8

  #define TIMER_PRESCALER 72  // 72MHZ STM32 clock div 72 --> timer clock 1MHz
  #endif


#ifdef TARGET_MATEK_CRSF_PWM_V10
  #define LED_BUILTIN PC14
  #define LED_ACTIVE_LOW true
  HardwareSerial Serial1(USART1); // PB6, PB7, TX, RX
  HardwareSerial Serial2(USART2); // PA2, PA3 TX, RX
  #define SERIAL1_TX PB6
  #define SERIAL1_RX PB7
  #define SERIAL2_TX PA2
  #define SERIAL2_RX PA3

  uint32_t PWM_Tim_Pin_Map[10] = {PA0,PA1,PB8,PC6,PB1_ALT1,PB0_ALT1,PA7,PA6,PA8,PB3}; // Pins used for PWM outputs 1..10 for some reason PB0 is conflicting with PA8 and  PA7 with PB3
  #define SDA1 PA12
  #define SCL1 PA11

  #define TIMER_PRESCALER 64  // 64MHZ STM32 clock div 64 --> timer clock 1MHz
#endif


#ifdef TARGET_MATEK_CRSF_PWM_V10
/**
  * @brief System Clock Configuration - internal RC oscillator + PLL - generated by STM32CubeMX 
  * @retval None
  */

extern "C" void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSIDiv = RCC_HSI_DIV2;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = RCC_PLLM_DIV1;
  RCC_OscInitStruct.PLL.PLLN = 8;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV4;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }
  
  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK|RCC_CLOCKTYPE_PCLK1;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
} 
#endif // TARGET_MATEK_CRSF_PWM_V10

#ifdef TARGET_BLUEPILL
/**
  * @brief System Clock Configuration
  * @retval None
  */
extern "C" void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.HSEPredivValue = RCC_HSE_PREDIV_DIV1;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL9;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
}

#endif // TARGET_BLUEPILL
